# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7492d0700eafdf9a76a396ab4a9aa8a937cbc449fc0645e2a5dd3f66043c563b974d5774c35e155ae46e27a37587ede48c74ca476dadbdb7ab7703f886cb1d2b

test:
  secret_key_base: 535ff8c6ffbec34108a8bbb9f0986c478f7fd719a42709e8d61b0d786d8a47059680342b8832cba301eb51615f23f61f7ce1a0906f2c50cca9e54f243d52f13b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
